version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@skip-go/widget"
      - dependency-name: "chain-registry"
      - dependency-name: "@initia/initia-registry"
