import { defineChain } from "viem";
import {
  arbitrum,
  arbitrumSepolia,
  avalanche,
  avalancheFuji,
  base,
  baseSepolia,
  blast,
  blastSepolia,
  bsc,
  celo,
  Chain,
  fantom,
  filecoin,
  kava,
  linea,
  mainnet,
  manta,
  moonbeam,
  optimism,
  optimismSepolia,
  polygon,
  polygonMumbai,
  sepolia,
} from "wagmi/chains";

export const forma = /*#__PURE__*/ defineChain({
  id: 984122,
  name: "Forma Mainnet",
  nativeCurrency: { name: "TIA", symbol: "TIA", decimals: 18 },
  rpcUrls: {
    default: {
      http: ["https://rpc.forma.art"],
    },
  },
  testnet: false,
});

export const EVM_CHAINS: Chain[] = [
  arbitrum,
  avalanche,
  base,
  bsc,
  celo,
  fantom,
  filecoin,
  kava,
  linea,
  mainnet,
  manta,
  moonbeam,
  optimism,
  polygon,
  polygonMumbai,
  sepolia,
  avalancheFuji,
  baseSepolia,
  optimismSepolia,
  arbitrumSepolia,
  blast,
  blastSepolia,
  forma,
];
