name: Deploy (dev)
on:
  pull_request:
    branches: [main]
    types: [closed]
  push:
    branches: [main]
  repository_dispatch:
    types: [deploy-dev]
  workflow_dispatch:

jobs:
  sync:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - id: configure
        name: Configure git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - id: sync-dev
        name: Sync 'main' → 'dev'
        run: |
          git fetch origin dev:dev || git branch dev
          git checkout dev
          git reset --hard origin/main
          git push --force origin dev
